### ISSUE TITLE
Проектно-конструкторская часть

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#10]
3.	Проектно-конструкторская часть

3.1.	 Реализация готового приложения.
	Для решения задач и создания приложения, обладающего всеми вышеперечисленными функциями, необходимо решить, как будут применяться для решения задач СУБД Postgres и Python Django.

3.2.	 Разработка и реализация структуры базы данных
Для реализации структуры базы данных была разработана его логическая схема. Данная схема приведена ниже:
 
![image](https://user-images.githubusercontent.com/106116687/206978897-62fc4d42-b320-4747-a243-0482b93dd8b3.png)
Схема 3.1 – Логическая схема БД
Таблицы были реализованы с помощью Django.

3.3.	 Разработка структуры приложения
	С помощью моделей в model.py создается описание таблицы в Django. Описание таблицы состоит из: названия таблицы, названий столбцов, описание типов данных столбцов. Пример описания таблицы:
class Ad(models.Model):
    mark = models.CharField('Марка', max_length=50)
    model = models.CharField('Модель', max_length=50)
    age = models.IntegerField('Год')
    body = models.CharField('Кузов', max_length=50)
    shift = models.CharField('КПП', max_length=50)
    mileage = models.IntegerField('Пробег')
    engine = models.CharField('Двигатель', max_length=50)
    volume = models.CharField('Объем двигателя', max_length=50)
    driveunit = models.CharField('Привод', max_length=50)
    vin = models.CharField('VIN', max_length=17)
    city = models.CharField('Город', max_length=50)
    price = models.IntegerField('Цена')
    comment = models.CharField('Комментарий', max_length=1000, null=True)
    image = models.ImageField('Фото', upload_to='main/img/imgavto', default='main/img/a.jpg')
    profile = models.ForeignKey('Profiles', on_delete=models.SET_NULL, null=True, verbose_name="Пользователь")

Данный класс содержит следующие элементы:
•	У класса присутствует параметр, который показывает, что класс является моделью таблицы (models.Model).
•	 Описание столбцов таблицы имеют следующие параметры:
o	Наименование столбца для административной панели
o	max_length = 50 – максимальная длинна данных в столбце.
o	null=True – может ли в данном столбце находится значение Null
o	Для внешнего ключа (ForeignKey) необходимы такие параметры, как название модели (класса), к которому необходимо привязать данную модель, и указать инструкцию on_delete=models.SET_NULL. Инструкция срабатывает в том случае, если экземпляр из таблицы Profiles удалили, а поле profile отсылался на данный экземпляр. При models.SET_NULL всем экземплярам таблицы присвоит значение Null. Также есть и инструкция models.CASCADE, которая удаляет все экземпляры таблицы Ad, который ссылались на удаленный экземпляр класса Profiles.
Чтобы модели появились в Postgres в виде таблиц необходимо сделать миграции. По завершению миграций Django автоматически создаст таблицу с первым столбцом «id».

3.4.	 Разработка алгоритмов обработки информации
	Основной задачей сайта, работающего с базами данных, является запись данных в таблицы и вывод этих данных.
В пример записи данных можно привести добавление объявления в раздел «Избранное».
Алгоритм записи данных:
def addfavorite(request, user_id, ad_id):
    for el in Favorites.objects.all():
        if (user_id == el.profile.id) & (ad_id == el.ad.id):
            return redirect('home')
    addf = get_object_or_404(Ad, pk=ad_id)
    prf = get_object_or_404(Profiles, pk=user_id)
    f = Favorites()
    f.ad = addf
    f.profile = prf
    f.save()
    return redirect('home')

В алгоритме стоит обратить внимание:
•	Проверка нахождения объявления в разделе «Избранное». Если объявление еще не добавлено, то начинается алгоритм добавления объявления. 
•	Функция get_object_or_404 отвечает за получение экземпляров объявления и профиля.
•	Экземпляры классов Ad и Profiles присваиваются соответственно к полям f.ad и f.profile.
•	Сохранение полученных данных происходит с помощью функции f.save().
Примером вывода данных будет обработчик:
def favorite(request):
    fad = Favorites.objects.all()
    return render(request, 'main/favorite.html', {'fad': fad})

Данный обработчик получает список избранных объявлений. После чего данный список отправляется в контекст html, где потом с помощью цикла и проверки на то, что эти объявления принадлежат авторизированному пользователю перебираются избранные объявления:
{% for fel in fad %}
{% if user.pk == fel.profile.pk %}
	...

{% endif %}
{% endfor %}

3.5.	 Разработка интерфейса взаимодействия пользователя с системой
	Взаимодействие пользователя с системой будет производиться с помощью использования веб интерфейса.
	Элементом графического интерфейса сайта, использующего инструменты html, css, является html страница. На сайте элементами управления являются: элементы для отправки формы, для переадресации на другую страницу сайта и т.д.
	Обычно сайты состоят из 3-х блоков: header, body, footer. На данном сайте имеются только 2 блока header и body. Блок header одинаков практически для всех страниц сайта, не включая страниц регистрации, входа.
	В блоке header находятся основная навигация сайта: Профиль, Размещение объявления, Основная страница с объявлениями, Избранное, «Мои объявления». Стоит учесть, что все эти пункты доступны только авторизированному пользователю. Если пользователь не зарегистрировался или не вошел в аккаунт, то в левой части header будет расположена кнопка «Войти/Зарегистрироваться», после нажатия которой пользователь может либо войти на сайт, либо зарегистрироваться. Если пользователь авторизовался, то вместо кнопки «Войти/Зарегистрироваться» уже будет отображаться поле с его ФИО, указанным при регистрации, нажав на которую он перейдет в настройки личных данных. 

![image](https://user-images.githubusercontent.com/106116687/207309683-c0458522-97ab-408a-8a90-c090027a8923.png)
Рисунок 3.1 – Header сайта
	
В блоке body располагается основной контент сайта, который уже является уникальным на каждой странице. Основные страницы, в которых пользователь может взаимодействовать:
•	«Разместить объявление»: расположена форма создания нового объявления о продаже автомобиля.
 
![image](https://user-images.githubusercontent.com/106116687/207309724-9f56b99d-4428-4cfe-ad24-e9347d3a729d.png)
Рисунок 3.2 – Страница создания объявления

•	«Объявления»: главная страница, которая загружается при входе на сайт, здесь отображается список объявлений, которые создали пользователи.
 
![image](https://user-images.githubusercontent.com/106116687/207309789-c08ebf1f-3b33-42e9-944d-c2a0d24a3457.png)
Рисунок 3.3 – Страница «Объявления»

•	«Избранное»: раздел, в котором хранятся объявления, которые заинтересовали пользователя. 
 
![image](https://user-images.githubusercontent.com/106116687/207309853-d3f822fd-2c75-4efd-950b-4ae8d179f652.png)
Рисунок 3.4 – Страница «Избранное»

•	«Мои объявления»: расположен список объявлений, которые создал конкретный пользователь.
 
![image](https://user-images.githubusercontent.com/106116687/207309890-25a74607-aa71-412d-b006-8b4ac3d36f1c.png)
Рисунок 3.5 – Страница «Мои объявления»

•	«Настройки профиля»: здесь находятся личные данные пользователя, а также две кнопки: «Изменить», при нажатии которой пользователь может поменять свои личные данные и «Выйти из аккаунта», при нажатии которой пользователь выйдет из аккаунта.
 
![image](https://user-images.githubusercontent.com/106116687/207309929-7aa5d4cf-7c9c-4c63-9bff-f2184372b4ed.png)
Рисунок 3.6 – Страница «Настройки профиля»

•	«Изменение данных: страница, на которой располагается форма, с помощью которой пользователь может изменить свои личные данные.
  
![image](https://user-images.githubusercontent.com/106116687/207309966-d836e1ca-099f-4868-a471-27b33584180d.png)
Рисунок 3.7 – Страница «Изменение данных»

•	«Вход»: страница, на которой расположена форма авторизации пользователя на сайте.
 
![image](https://user-images.githubusercontent.com/106116687/207309994-af610c79-d25c-45c1-8205-2e44aadcd16c.png)
Рисунок 3.8 – Страница авторизации

•	«Регистрация»: страница с формой регистрации пользователя на сайте.
 
![image](https://user-images.githubusercontent.com/106116687/207310031-746c8c75-b88b-498f-875a-275574ca74da.png)
Рисунок 3.9 – Страница регистрации

**Comment by wldmr-key** [comment]
иллюстрацией к алгоритму могла бы быть блок-схема, но это, возможно, к курсовой по архитектуре
