### ISSUE TITLE
Проектно-технологическая часть

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#11]
Таблицы сюда не хотят выкладываться, поэтому просто оставлю здесь Word документ.

[proektno-technologicheskaya_Polyakov.docx](https://github.com/PolyakovYan11/KR_Avto/files/10261125/proektno-technologicheskaya_Polyakov.docx)

**Comment by wldmr-key** [comment]
можно было и не выкладывать таблицы. А хостинг ты выбрал стремный, но даже там разворачивание не так просто, как ты написал )
сойдет
