### ISSUE TITLE
Заключение и список литературы

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#12]
Заключение

В ходе выполнения данной курсовой работы были решены задачи и была достигнута цель проекта. Была разработана система, реализующая функции:
•	Отправка данных в БД
•	Обработка данных
•	Извлечение данных из БД
В будущем проект будет получать обновления, которые будут включать появление новых функции и исправление недочётов внешнего вида, безопасности и некоторых алгоритмов. В частности:
•	Добавление панели администратора.
•	Более подробное описание объявлений.
•	Уникальный внешний вид.
•	Улучшение функционала фильтра.
 
Список литературы

1.	Шнырёв, С.Л.  Базы данных: учебное пособие для вузов - М.: НИЯУ МИФИ, 2011. — 224 с. — Режим доступа: http://e.lanbook.com/book/75809 
2.	Ревунков, Г.И. Базы и банки данных - М.: МГТУ им. Н.Э. Баумана, 2011. — 68 с. — Режим доступа: http://e.lanbook.com/book/52425 
3.	Ревунков, Г.И. Проектирование баз данных - М.: МГТУ им. Н.Э. Баумана, 2009. — 20 с. — Режим доступа: http://e.lanbook.com/book/52390 
4.	Кудрявцев, К.Я.  Создание баз данных: учебное пособие — М.: НИЯУ МИФИ, 2010. — 155 с. — Режим доступа: http://e.lanbook.com/book/75822 
5.	Сидоров В.Н., Сломинская Е.Н., Полникова Т.В., Макарова О.Ю. Оформление графической части выпускной квалификационной работы. Учебное пособие. М.: МГТУ им. Н.Э. Баумана, 2016.
6.	Руководство по веб-фреймворку Django [Электронный ресурс]. – URL: https://metanit.com/python/django/
7.	Django Documentation [Электронный ресурс]. – URL: https://docs.djangoproject.com/en/4.1/
8.	Htmlbook.ru [Электронный ресурс]. – URL: http://htmlbook.ru/html

**Comment by wldmr-key** [comment]
норм
