### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#2]
1.Техническое задание

1.1. Общие сведения:

1.1.1. Полное наименование системы:
Сайт по размещению объявлений о продаже автомобилей

1.1.2. Наименования организации-заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-52Б Поляков Я.А.

1.1.3. Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ – 12 сентября 2022 года.
Плановый срок окончания работ – 1 декабря 2022 года.

1.2. Назначение и цели создания системы

1.2.1. Назначение системы:
Система предназначена для размещения объявлений о продаже автомобиля или поиска автомобиля для дальнейшей покупки.

1.2.2. Цели создания системы:
Система создается для ускоренной продажи или покупки автомобиля.

1.3. Требования к системе

1.3.1. Требования к системе в целом:

1.3.1.1. Требования к структуре и функционированию системы:
Система разделена на 4 подструктуры:
- Клиентская часть в виде веб-приложения.
- Место хранения данных (база данных).
- Серверная часть веб-сайта.
- Хостинг

1.3.1.2.	Требования по эргономике и технической эстетике:
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе. Интерфейс должен быть понятен и не перегружен графическими элементами.

1.3.2.	 Требования к функциям (задачам), выполняемым системой

- Авторизация на веб-сайте.
- Адекватное отображение контента (Текстов, изображений) на мобильных устройствах и ПК
- Размещение объявлений
- Просмотр размещенных объявлений
- Управление профилем
- Изменение объявлений
- Удаление объявлений
- Добавление объявлений в раздел «Избранное»
- Удаление объявлений из раздела «Избранное» 

1.3.3.	 Требования к видам обеспечения

1.3.3.1.	Требования к лингвистическому обеспечению системы
	Средством описания предметной области, также, как и средством взаимодействия пользователя с системой является русский язык.

1.3.3.2.	Требования к входным и выходным данным

Входными данными системы от пользователя браузера являются ФИО, почта, номер телефона, пароль и данные об автомобиле. Выходными данными являются объявления, размещенные другими пользователями.

1.3.3.3.	Требования к программному обеспечению системы

В качестве языка программирования для разработки серверной части в системе используется Python Django, для работы с СУБД - Postgres, для создания пользовательского интерфейса используется HTML и CSS.
Наличие браузера - обязательное требование.

1.4. Состав и содержание работ по созданию (развитию) системы

1.	Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса (1 – 4-я недели).
2.	Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД (5 – 7-я недели).
3.	Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и откладка приложения. Разработка эксплуатационной документации. (8 – 10-я недели).
4.	Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы (11 – 14-я недели).

1.5.	 Порядок контроля и приемки системы

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.

1.6.	 Требования к документированию
Требуется предоставить:
1. Техническое задание в соответствии с ГОСТ 34.602-89
2. Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
Неплохо, но

> 1.2.2. Цели создания системы:
Система создается для комфортной и ускоренной продажи или покупки автомобиля.

То есть это благотворительный сайт? )) Так и напиши - цель помочь людям )) 

> Клиентская часть в виде веб-сайта.
Серверная часть веб-сайта.

так не бывает. Клиентская часть - веб-приложение

> Требования к функциям (задачам), выполняемым системой

маловато функций. Справочниеов никаких не будет? Модерирования не будет? Администрирования не будет? Объявления удаляться не будут?

Базы данных в системе будут? Из текста не очевидно

**Comment by wldmr-key** [comment]
отсутствует описание объекта автоматизации. Будут ли у системы администраторы? Какие у них функции? У покупателей и продавцов разные функции? из описани яэтого не видно
