### ISSUE TITLE
Описание предметной области и требований к системе

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#4]
Предметная область: сайт по продаже поддержанных автомобилей.

У людей есть потребность в покупке нового автомобиля, при этом не каждый человек имеет возможность и желание покупать новый автомобиль из автосалона у официального дилера. На это может быть множество причин, например высокая наценка на автомобиль или же покупка первого автомобиля, так как люди получившие права не сразу обладают высокими навыками вождения и есть вероятность причинить ущерб автомобилю.
 
С другой стороны, некоторые люди желают купить себе новый автомобиль из автосалона, для этого многие продают свой старый автомобиль, чтобы заработать с него денег или освободить место в гараже для нового автомобиля.

Требования к системе.
Система должна соответствовать следующим требованиям:
1.	Наличие авторизации на сайте
2.	Адаптация сайта для всех устройств
3.	Наличие базы данных для хранения объявлений, информации с аккаунтов пользователей.

Первый пункт необходим для возможности выкладывать объявления, а также для использования всех возможностей сайта. При регистрации от пользователя требуется ФИО, почта, номер телефона и пароль. Почта необходима для дальнейшего входа на сайт. ФИО и номер телефона необходимы для отображения в объявлении, которое выложил пользователь и для связи покупателя и продавца, в случае если пользователя устроил автомобиль, и он хочет провести личную встречу с целью осмотра автомобиля и дальнейшего приобретения. 

Второй пункт необходим для отображения сайта на всех устройствах. Сайт должен быть адаптирован под все устройства, в частности смартфоны, так как пользователь должен иметь доступ к сайту в любом месте, например при осмотре автомобиля, чтобы сверить данные, указанные на сайте с действительными характеристиками, что также поможет избежать мошенничества и дальнейших проблем с эксплуатацией и постановкой на учёт автомобиля. 

Третий пункт необходим для долговременного хранения информации, так как продажа/покупка автомобиля – процесс не быстрый. Соответственно для того, чтобы БД была связана с сайтом, необходимо написать соответствующий код.

**Comment by wldmr-key** [comment]
Ян, еще раз - описание предметной области - это описание продажи автомобилей - как она происходит без всякуого твоего сайта (барахолки, гаражи, салоны, газеты и т.д.). Что интересует покупателя, что продавца, какие харктеристики важны и т.п.
После введения понятий предметной области ты уже делаешь выводы, что сайт - это лучше  (?) и формулируешь/обосновываешь требования к разрабатываемой системе.
Поэтому, все, что ты написал (в принципе, правильно, хотя и несколько сумбурно) лучше бы привести в соответствие с этим каноном.
