### ISSUE TITLE
Анализ аналогов

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#5]
Анализ аналогов.
Для примерного представления о внешнем виде рассмотрены такие сайты, как Авто.ру (https://auto.ru/), Авито (https://www.avito.ru/). 
1. На сайте Авто.ру удобно реализован фильтр поиска автомобилей, также лента с объявлениями.
![image](https://user-images.githubusercontent.com/106116687/194922392-ff62dd1b-5413-46d8-8fee-30084a470084.png)
![image](https://user-images.githubusercontent.com/106116687/194922446-ff6e70a0-bcc9-44ef-ae0a-c95451c73a7f.png)

2. На сайте Авито удобный и максимально простой в использовании интерфейс личного кабинета, избранных объявлений, настройки аккаунта.
 
![image](https://user-images.githubusercontent.com/106116687/194922536-16603378-6ad9-4b6d-b0f0-7b8dfb731d49.png)
![image](https://user-images.githubusercontent.com/106116687/194922560-6f07f495-836f-4f66-87db-76e5e0445ce8.png)

Также функционал создания объявления будет взят с сайта Авто.ру (https://auto.ru/), так как Авито не специализируется только на автомобильных объявлениях, что для моего проекта не совсем подходит.

![image](https://user-images.githubusercontent.com/106116687/202154136-a4a25933-4b1e-47b6-ba3a-efac0a0a4bf5.png)

В отличие от Авто.ру создаваться объявления в проекте будут без изначальных справочников марок и моделей автомобилей, они будут заполняться по мере выставления объявлений и при редактировании объявлений администратором сайта. Соответственно данные справочники будут использоваться только при поиске автомобиля через фильтр объявлений.  
 
Пользовательский интерфейс вышеуказанных сайтов мне кажется немного перегруженным информацией, поэтому в данном проекте страницы будут иметь минималистический вид, чтобы максимально упростить пользование сайтом.

![image](https://user-images.githubusercontent.com/106116687/202157187-189a3fc0-d256-4eb7-91eb-f0f6bef83bc1.png)
![птыт](https://user-images.githubusercontent.com/106116687/202157410-b4167177-df48-404b-a247-b39dea3acdf7.png)

**Comment by wldmr-key** [comment]
начало хорошее. Еще немного и общие выводы
