### ISSUE TITLE
Прототипы и скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#6]
1. Страница профиля пользователя

![image](https://user-images.githubusercontent.com/106116687/202148482-beb08ebb-f8f7-4658-9a0b-14f01d310a21.png)

2. Страница избранных объявлений

![image](https://user-images.githubusercontent.com/106116687/202148789-7b2370eb-99ae-4172-a343-f1c886cc095c.png)

3. Основная страница

![image](https://user-images.githubusercontent.com/106116687/202149079-baea899d-e9bb-415b-b5ab-84b703db8923.png)
![image](https://user-images.githubusercontent.com/106116687/202149018-f948c573-e29f-4f82-ac77-02f6197996b3.png)

4. Страница создания объявления

![image](https://user-images.githubusercontent.com/106116687/202149278-f0fb5340-dd3c-4f24-aaca-5f32b2d4ac79.png)
![image](https://user-images.githubusercontent.com/106116687/202149410-176fedf0-f914-4de2-8765-bc0d88459362.png)

5. Страница настроек профиля

![image](https://user-images.githubusercontent.com/106116687/202149834-1453c3e3-3cc7-41f1-89da-2e9cc8a3ab9b.png)

6. Страница изменения личных данных

![image](https://user-images.githubusercontent.com/106116687/202150223-96cecb71-0e47-4547-a172-e76522496492.png)

7. Страница входа на сайт

![image](https://user-images.githubusercontent.com/106116687/202150408-822edd7e-58be-46ed-b168-25ceac76e9b5.png)

**Comment by wldmr-key** [comment]
норм
