### ISSUE TITLE
Концептуальная модель предметной области 

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#7]
![image](https://user-images.githubusercontent.com/106116687/206929016-fbaa88f9-cce0-48d5-b193-d3cd34ee9af8.png)

**Comment by wldmr-key** [comment]
Что за адская фраза "Объявления и Профили зависят друг к другу связью" в которой слова никак ждруг с другом не вяжутся?! Ты уже почти все сказал в описании предметной области

Лучше скажи, разве избранные объявления - это не те же объявления?

**Comment by PolyakovYan11** [comment]
Избранные объявления - это те же объявления, но они хранятся в отдельной таблице, поэтому я и подумал, что нужно их выделить в отдельную сущность.

**Comment by wldmr-key** [comment]
Я надеюсь в отдельной таблице у тебя хранится ид.профиля и ид.объявления. Это на логическом уровне

На концептуальном - это просто связь многи ко многи между объявлениями и профилями, которая назвается "избрал-было избрано"

**Comment by PolyakovYan11** [comment]
Да, в отдельной таблице хранится ид.профиля и ид.объявления)
Схему исправил.
