### ISSUE TITLE
Научно-исследовательская часть

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#8]
2.	Научно-исследовательская часть

2.1.	Постановка задачи проектирования
	Задачами проектирования являются:
1.	Спроектировать модель базы данных.
2.	Разработать клиентскую часть приложения.
3.	Разработать бизнес-логику приложения.
4.	Разработать серверную часть приложения.
5.	Оформить документацию.

2.2.	Описание предметной области
У людей есть потребность в покупке нового автомобиля, при этом не каждый человек имеет возможность и желание покупать новый автомобиль из автосалона у официального дилера. На это может быть множество причин, например высокая наценка на автомобиль или же покупка первого автомобиля, так как люди получившие права не сразу обладают высокими навыками вождения и есть вероятность причинить ущерб автомобилю. 

С другой стороны, некоторые люди желают купить себе новый автомобиль из автосалона, для этого многие продают свой старый автомобиль, чтобы заработать с него денег или освободить место в гараже для нового автомобиля.
Все эти факторы выявляют необходимость реализации проекта.
 
2.3.	Анализ аналогов и прототипов
Для примерного представления о внешнем виде рассмотрены такие сайты, как Авто.ру (https://auto.ru/), Авито (https://www.avito.ru/)
Перечисленные ниже пункты послужили основой для разработки визуальной части некоторых страниц:
1.	На сайте Авто.ру удобно реализован фильтр поиска автомобилей, также лента с объявлениями.
 
![image](https://user-images.githubusercontent.com/106116687/206915841-7b4b6f1e-628b-4f25-97d1-8dc47942fb9a.png)
Рисунок 2.1 – Фильтр сайта Авто.ру
 
![image](https://user-images.githubusercontent.com/106116687/206915857-8a2df0a7-f1a7-45dd-925d-9903aad3ce5a.png)
Рисунок 2.2 – Лента объявлений на сайте Авто.ру

2.	На сайте Авито удобный и максимально простой в использовании интерфейс страниц «Мои объявления», «Избранное».
 
![image](https://user-images.githubusercontent.com/106116687/206915923-1e1bcb92-1047-4ce1-a465-6ef702139c89.png)
Рисунок 2.3 – Страница «Мои объявления» на сайте Авито

![image](https://user-images.githubusercontent.com/106116687/206915970-130bf4c6-ab95-4fb6-afff-0b593f0a7060.png) 
Рисунок 2.4 – Страница «Избранное» на сайте Авито

3.	Также функционал создания объявления будет взят с сайта Авто.ру (https://auto.ru/), так как Авито не специализируется только на автомобильных объявлениях, что для данного проекта не совсем подходит. В отличие от Авто.ру создаваться объявления в проекте будут без изначальных справочников марок и моделей автомобилей.

![image](https://user-images.githubusercontent.com/106116687/206915994-9671bf1e-d598-46a6-9ca5-c61ce7da89e6.png)
Рисунок 2.5 – Страница создания объявления на сайте Авто.ру

4.	Пользовательский интерфейс вышеуказанных сайтов кажется мне немного перегруженным информацией, поэтому в данном проекте страницы будут иметь минималистичный вид, чтобы максимально упростить пользование сайтом.
 
![image](https://user-images.githubusercontent.com/106116687/206916035-a128dfe3-164a-4c28-a71d-dbbdfcea265f.png)
Рисунок 2.6 – Главная страница сайта Авто.ру
 
![image](https://user-images.githubusercontent.com/106116687/206916043-29d93a12-569a-4b70-a7a7-b39089d54f75.png)
Рисунок 2.7 – Главная страница сайта Авито

Остальные пункты, такие как настройки профиля, изменение данных профиля, страница объявления были реализованы самостоятельно.
 
2.4.	Перечень задач, подлежащих решению в процессе разработки
	Перечень задач:
●	Описать предметную область.
●	Проанализировать аналоги.
●	Спроектировать концептуальную модель предметной области.
●	Спроектировать логическую модель.
●	Выбрать инструменты для разработки клиентской части и бизнес-логику.
●	Изучить выбранные инструменты.
●	Разработать клиентскую часть.
●	Разработать бизнес-логику.
●	Разработка северной части.
●	В процессе разработки проекта оформить документацию к нему.

2.5.	Концептуальная схема данных
 
![image](https://user-images.githubusercontent.com/106116687/206929208-8e66028f-ccb1-4ffa-9240-a85eb98a6abd.png)
Схема 2.1 – Концептуальная схема БД

2.6.	Требования к приложению
Система должна соответствовать следующим требованиям:
1.	Наличие авторизации на сайте
2.	Адаптация сайта для всех устройств
3.	Наличие базы данных для хранения объявлений, информации с аккаунтов пользователей.

Первый пункт необходим для возможности выкладывать объявления, а также для использования всех возможностей сайта. При регистрации от пользователя требуется ФИО, почта, номер телефона и пароль. Почта необходима для дальнейшего входа на сайт. ФИО и номер телефона необходимы для отображения в объявлении, которое выложил пользователь и для связи покупателя и продавца, в случае если пользователя устроил автомобиль, и он хочет провести личную встречу с целью осмотра автомобиля и дальнейшего приобретения. 

Второй пункт необходим для отображения сайта на всех устройствах. Сайт должен быть адаптирован под все устройства, в частности смартфоны, так как пользователь должен иметь доступ к сайту в любом месте, например при осмотре автомобиля, чтобы сверить данные, указанные на сайте с действительными характеристиками, что также поможет избежать мошенничества и дальнейших проблем с эксплуатацией и постановкой на учёт автомобиля. 

Третий пункт необходим для долговременного хранения информации, так как продажа/покупка автомобиля – процесс не быстрый. Соответственно для того, чтобы БД была связана с сайтом, необходимо написать соответствующий код.

**Comment by wldmr-key** [comment]
пойдет, только с концептуальной схемой разберись
