### ISSUE TITLE
Логическая схема БД

### ISSUE THREAD

**Issue by PolyakovYan11** [PolyakovYan11/KR_Avto#9]
![image](https://user-images.githubusercontent.com/106116687/206978897-62fc4d42-b320-4747-a243-0482b93dd8b3.png)

**Comment by wldmr-key** [comment]
риторический вопрос на пятерку )
Чем обосновано применение таблиц из одного столбца?

**Comment by PolyakovYan11** [comment]
Эти таблицы сделаны отдельно, потому что пользователь при заполнении формы не вводит эти данные вручную, ему предлагается выбор, соответственно нужно постоянно хранить эти данные и если понадобится обновлять. Поэтому можно конечно от них избавиться, но тогда это будет лежать в виде списков в коде, что не есть хорошо)
